services:
  # Glavni portfolio site
  portfolio-site:
    build:
      context: ./portfolio-site
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./portfolio-site:/app
    environment:
      SERVER_NAME: :80

  # Eko-Kos projekt (čisti, statični web server)
  eko-kos-site:
    image: caddy:alpine
    ports:
      - "8081:80"
    volumes:
      - ./eko-kos/dist:/usr/share/caddy

    # NEMA POTREBE ZA Caddyfile-om: Ako koristiš službeni caddy:alpine image za eko-kos-site,
    # on ima predefiniranu postavku da sve što baciš u /usr/share/caddy automatski servira na portu 80 tog kontejnera (što je izvana tvoj 8081). Ne moraš pisati nikakav konfiguracijski file.

  # Verzija 1: Čisti HTML/CSS/JS (Statično)
  sounwave-v1:
    image: caddy:alpine
    ports:
      - "8082:80"
    volumes:
      - ./soundwave/v1/:/usr/share/caddy

  # Verzija 2: PHP varijanta (Koristimo FrankenPHP)
  soundwave-v2:
    build:
      context: ./soundwave/v2
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ./soundwave/v2:/app/public # FrankenPHP po defaultu servira iz /app foldera
    environment:
      SERVER_NAME: :80

  # Soundwave-v2 DB
  soundwave-v2-db:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: soundwave_v2
      MARIADB_USER: soundwave
      MARIADB_PASSWORD: soundwave
    volumes:
      - soundwave-v2-db-data:/var/lib/mysql
      # Automatski uvezi SQL dump pri prvom pokretanju baze:
      - ./soundwave/v2/admin/db/soundwave_loc.sql:/docker-entrypoint-initdb.d/dump.sql

  # Verzija 3: React App (Statični produkcijski build)
  soundwave-v3:
    image: caddy:alpine
    ports:
      - "8084:80"
    volumes:
      - ./soundwave/v3/dist:/usr/share/caddy
      - ./soundwave/v3/Caddyfile:/etc/caddy/Caddyfile

  # Soundwave-v3 DB
  soundwave-v3-db:
    image: mariadb:10.4.32
    ports:
      - "3307:3306" # Otvaramo port 3307 na računalu da se ne tuče s v2 bazom na 3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: soundwave_v3
      MARIADB_USER: soundwave
      MARIADB_PASSWORD: soundwave
    volumes:
      - soundwave-v3-db-data:/var/lib/mysql
      # Automatski uvezi SQL dump pri prvom pokretanju baze:
      - ./soundwave/v3/backend/db/soundwave.sql:/docker-entrypoint-initdb.d/dump.sql

  # Express Backend za v3 verziju
  soundwave-v3-backend:
    build:
      context: ./soundwave/v3
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./soundwave/v3/backend:/app
      - /app/node_modules # Čuva pakete unutar kontejnera da ih lokalni folder ne pregazi
    env_file:
        - ./soundwave/v3/.env
    environment:
      PORT: 4000
      DB_HOST: soundwave-v3-db
      DB_USER: soundwave
      DB_PASSWORD: soundwave
      DB_NAME: soundwave_v3

volumes:
  soundwave-v2-db-data:
  soundwave-v3-db-data: